change deprecated `@elseif` to `@else if`
drublic/Sass-Mixins pull request #49
Opened 2019-01-31 14:40 UTC by grafmouse

2019-01-31 15:53 UTC, drublic requested changes
Thanks for the nice contribution. Please update the things I outlined and we’re good to merge :)

2019-01-31 15:53 UTC, drublic commented on test/css/main.css
> +  font-size: 1.3 * 1rem;
This looks like something is wrong here.

2019-01-31 15:53 UTC, drublic commented on test/css/main.css
> +  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=40)";
I think we don’t need to support old IE.

2019-01-31 15:53 UTC, drublic commented on test/css/main.css
> +  padding: 16 * 1px 0 48px;
Same as above. also see below.

2019-01-31 15:53 UTC, drublic commented on CHANGELOG.md
> +### 0.13.0 - 31.01.2019
I think i need to do another version here after merging. so you can skip this line for now.

2020-03-30 08:19 UTC, towry commented
https://github.com/drublic/Sass-Mixins/issues/50

2020-03-30 09:18 UTC, closed without merging

2020-03-30 09:18 UTC, drublic commented
Merged.